home = '//div[@id="logo"]'
about = '//header//ul[contains(@class,"top-menu")]/li/a[contains(@href,"o-nas.html")]'
delivery_and_payment = '//header//ul[contains(@class,"top-menu")]/li/a[contains(@href,"dostavka-i-oplata.html")]'
menu = '//div[contains(@class,"mainmenublock")]//div[contains(@class,"mainmenu")]'
tactic_shoes = '//div[contains(@class,"mainmenu")]/ul[@class="list-unstyled"]/li/a[contains(@href,"katalog/obuv")]'
guard_clothes = '//div[contains(@class,"mainmenu")]/ul[@class="list-unstyled"]/li/a[contains(@href,"katalog/forma-ohranyi")]'
police_uniform = '//div[contains(@class,"mainmenu")]/ul[@class="list-unstyled"]/li/a[contains(@href,"katalog/dlya-politsii")]'
open_police_accessories = '//div[@class="col-xs-12"]/div/ul/li//a[contains(@href,"aksessuaryi-dlya-politsii")]/p[contains(@style,"height:")]'
sneakers = '//div/a[contains(@href,"katalog/obuv/obuvv/krossovki")]/img'
fishing_hunting ='//div[contains(@class,"mainmenu")]/ul[@class="list-unstyled"]/li/a[contains(@href,"katalog/ryibalka-i-ohota/")]'
about_title = '//h1[@class="col-xs-12"]'