version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.17-browsers
    steps:
      - checkout
      - run: python --version

      - run:
          name: Install Python dependencies
          command: |
            pip install -r requirements.txt
            pip install selenium

      - run:
          name: Run tests
          command: |
            behave features/test

workflows:
  version: 2
  build:
    jobs:
      - build